//id de letras

import { setEventsOnLocal } from "./functions.js";

let eventsArray = [
	{
		id: "ny",
		allday: true,
		title: "New year",
		initial_date: "2021-01-0",
		final_date: 0,
		initial_time: 0,
		final_time: 0,
		alarm: false,
		reminder: false,
		description: "",
		type: "holiday",
	},
	{
		id: "kd",
		allday: true,
		title: "Kings Day",
		initial_date: "2021-01-06",
		final_date: 0,
		initial_time: 0,
		final_time: 0,
		alarm: false,
		reminder: false,
		description: "",
		type: "holiday",
	},
	{
		id: "sf",
		allday: true,
		title: "Sait Friday",
		initial_date: "2021-04-02",
		final_date: 0,
		initial_time: 0,
		final_time: 0,
		alarm: false,
		reminder: false,
		description: "",
		type: "holiday",
	},
	{
		id: "em",
		allday: true,
		title: "Easter monday",
		initial_date: "2021-04-05",
		final_date: 0,
		initial_time: 0,
		final_time: 0,
		alarm: false,
		reminder: false,
		description: "",
		type: "holiday",
	},
	{
		id: "ld",
		allday: true,
		title: "Labor Day",
		initial_date: "2021-05-01",
		final_date: 0,
		initial_time: 0,
		final_time: 0,
		alarm: false,
		reminder: false,
		description: "",
		type: "holiday",
	},
	{
		id: "sj",
		allday: true,
		title: "Saint john's day",
		initial_date: "2021-06-24",
		final_date: 0,
		initial_time: 0,
		final_time: 0,
		alarm: false,
		reminder: false,
		description: "",
		type: "holiday",
	},
	{
		id: "cd",
		allday: true,
		title: "Catalonia day",
		initial_date: "2021-09-11",
		final_date: 0,
		initial_time: 0,
		final_time: 0,
		alarm: false,
		reminder: false,
		description: "",
		type: "holiday",
	},
	{
		id: "hs",
		allday: true,
		title: "National holiday of Spain",
		initial_date: "2021-10-12",
		final_date: 0,
		initial_time: 0,
		final_time: 0,
		alarm: false,
		reminder: false,
		description: "",
		type: "holiday",
	},
	{
		id: "as",
		allday: true,
		title: "All Saints",
		initial_date: "2021-11-01",
		final_date: 0,
		initial_time: 0,
		final_time: 0,
		alarm: false,
		reminder: false,
		description: "",
		type: "holiday",
	},
	{
		id: "cd",
		allday: true,
		title: "Day of the Constitution",
		initial_date: "2021-12-06",
		final_date: 0,
		initial_time: 0,
		final_time: 0,
		alarm: false,
		reminder: false,
		description: "",
		type: "holiday",
	},
	{
		id: "ic",
		allday: true,
		title: "Immaculate Conception's Day",
		initial_date: "2021-12-08",
		final_date: 0,
		initial_time: 0,
		final_time: 0,
		alarm: false,
		reminder: false,
		description: "",
		type: "holiday",
	},
	{
		id: "ch",
		allday: true,
		title: "Christmas",
		initial_date: "2021-12-24",
		final_date: 0,
		initial_time: 0,
		final_time: 0,
		alarm: false,
		reminder: false,
		description: "",
		type: "holiday",
	},
];

function setPreSaved() {
  setEventsOnLocal(eventsArray, "pre-saved-events");
}

let newEventsArray = [];

function setNewEvents() {
  setEventsOnLocal(newEventsArray, "new-event");
}

export { setPreSaved, setNewEvents };
